### ISSUE TITLE
App not opening

### ISSUE THREAD

**Issue by venky1995** [sajjadjaved01/iptv#10]
Please Give me any read me text.. to proper set up of the android studio. I am facing an app error when i am opening its closing fraction of seconds....

**Comment by sajjadjaved01** [comment]
Post error

**Comment by venky1995** [comment]
How can I fix that error can u please provide a read me document for the app it help to proper set up of android app. Thankyou.

**Comment by sajjadjaved01** [comment]
can u post that error. if u cant post it, how will i know...

**Comment by venky1995** [comment]
Sir, code decomopiled great. While I entered the user and pass its accessed within seconds the app closed..

**Comment by sajjadjaved01** [comment]
if closed due to some exception / error then monitor error Log, & post it here. Or check server url, details ...
Thanks

**Comment by venky1995** [comment]
Sir, Actually I am new to this type of IPTV apps! I had Active M3u link and Dedicated server but i dont know how to configure!!!.. Please Help sir! thank you


D/AndroidRuntime: Shutting down VM
E/UncaughtException: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
                         at java.util.ArrayList.get(ArrayList.java:411)
                         at com.muparse.MainActivity$GetJson.onPostExecute(MainActivity.java:264)
                         at com.muparse.MainActivity$GetJson.onPostExecute(MainActivity.java:186)
                         at android.os.AsyncTask.finish(AsyncTask.java:667)
                         at android.os.AsyncTask.-wrap1(AsyncTask.java)
                         at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
                         at android.os.Handler.dispatchMessage(Handler.java:102)
                         at android.os.Looper.loop(Looper.java:154)
                         at android.app.ActivityThread.main(ActivityThread.java:6119)
                         at java.lang.reflect.Method.invoke(Native Method)
                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)


                     --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.muparse, PID: 4617
                  java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
                      at java.util.ArrayList.get(ArrayList.java:411)
                      at com.muparse.MainActivity$GetJson.onPostExecute(MainActivity.java:264)
                      at com.muparse.MainActivity$GetJson.onPostExecute(MainActivity.java:186)
                      at android.os.AsyncTask.finish(AsyncTask.java:667)
                      at android.os.AsyncTask.-wrap1(AsyncTask.java)
                      at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by venky1995** [comment]
Sorry to say sir. Actually i am completely confused sir. I am new to this integration process sir. Which server url did i need to place sir, time, and json where i need to upload etc...  Please can u please explain in detail for integration sir... Please don't mind bad sir..  thankyou.

**Comment by sajjadjaved01** [comment]
Okay let me see your m3u link...

**Comment by venky1995** [comment]
http://portal.simiptv.com:8001/get.php?username=LrWQISrOq0&password=7i5Qdtmunn&type=m3u&output=ts

**Comment by sajjadjaved01** [comment]
url is fine

**Comment by sajjadjaved01** [comment]
I'll check, but can't say

**Comment by venky1995** [comment]
Not understanding bro!!  +91 8801272205 its my WhatsApp number please come and help me bro
